import test from 'node:test';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import {readFileSync} from 'node:fs';
import {LocalDatabase,rows} from '../src/database.ts';
import type {Statement,Entry,Scan} from '../src/types.ts';
import {digest,mealSchema,prepareCommon,loadCloudRequirements,nextImportPart,uploadPart,unpackAsset} from '../src/meal-import.ts';
import type {MealRecord,MealManifest} from '../src/meal-import.ts';
import {DIETARY_POLICY} from '../src/dietary-policy.ts';
import {handle} from '../worker/index.ts';
import {publish} from '../src/publish.ts';
import {refreshIngredientLinks} from '../src/ingredient-publish.ts';
import {normalize} from '../src/products.ts';
import {calculateLine,aggregateShopping,canonicalAmount} from '../src/meal-cost.ts';
const readToken='private-read-test-token-longer-than-32-characters';
function binding(d:LocalDatabase){function prepare(sql:string){let params:Statement['params']=[];const s={sql,get params(){return params},bind(...p:NonNullable<Statement['params']>){params=p;return s},async first(){return(await rows(d,sql,params))[0]??null},async all(){return{results:await rows(d,sql,params),success:true}}};return s};return {prepare,batch:async(ss:ReturnType<typeof prepare>[])=>d.batch(ss.map(s=>({sql:s.sql,params:s.params})))} as unknown as D1Database;}
function fixtures(){
  const requirement=[{name:'eggs',occurrences:5},{name:'water',occurrences:5}],inventory={hash:digest(JSON.stringify(requirement)),requirements:requirement,ingredientOccurrences:10,recipes:5,dietaryPolicy:DIETARY_POLICY};
  const defs=[{filter_id:1,domain:'diet',key:'vegetarian'},{filter_id:2,domain:'allergen',key:'milk'},{filter_id:3,domain:'cuisine',key:'mexican'},{filter_id:4,domain:'cuisine',key:'nordic'},{filter_id:5,domain:'nutrition_feature',key:'protein_ge_20g'}];
  const common={inventory,definitions:defs,metadata:{fixture:true},classificationRuns:[],sourceCounts:{recipes:5,ingredients:10,reviews:5},subjects:requirement.map(r=>({...r,filters:[{filter_id:2,state:'no'}]})),sets:{'1:yes':[1,2,4,5],'1:unknown':[3],'2:no':[1,3,4,5],'2:unknown':[2],'3:yes':[1,2],'4:yes':[3,4],'5:yes':[1,4]}};
  const records:Array<MealRecord>=Array.from({length:5},(_,n)=>{
    const id=n+1;const document=JSON.stringify({source:{RecipeId:String(id),Name:'Recipe '+id,RecipeServings:2,RecipeYield:'two servings',Calories:100},ingredients:[{ingredient_index:0,ingredient_original:'eggs',unit:'count',measured_quantity:'3'},{ingredient_index:1,ingredient_original:'water',unit:'cup',measured_quantity:'1'}],quality:{state:'consistent'},filters:[{filter_id:1,state:id===3?'unknown':'yes'}],profile:{nutrition_metrics:{nutrients_per_serving:{Calories:100,ProteinContent:20}}},reviews:[{ReviewId:id,Review:'Review '+id}]}),summary=JSON.stringify({id,name:'Recipe '+id});return {id,name:'Recipe '+id,names:JSON.stringify(['eggs','water']),document,summary,hash:digest(document)};
  });
  const parts=records.map((r,i)=>({day:i+1,recipes:1,firstId:r.id,lastId:r.id,file:'day-'+(i+1)+'.gz',sha256:digest('part'+i),bytes:1,uncompressedBytes:1,maxEstimatedWrites:100}));
  const m={schemaVersion:1,datasetId:'a'.repeat(64),sourceSha256:'a'.repeat(64),recipes:5,ingredientOccurrences:10,distinctIngredients:2,reviews:5,inventoryHash:inventory.hash,filterSets:Object.keys(common.sets).length,parts,common:{file:'common.gz',sha256:'b'.repeat(64),bytes:1,uncompressedBytes:1},releaseTag:'fixture',repository:'test/repo',sourceCounts:common.sourceCounts} as MealManifest;
  return {m,common,records};
}
function setup(){const meal=new LocalDatabase(':memory:'),catalog=new LocalDatabase(':memory:');meal.execute(mealSchema());for(const name of ['0001_catalog.sql','0002_ingredients.sql'])catalog.execute(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));return {meal,catalog,...fixtures()};}
async function complete(s:ReturnType<typeof setup>){await prepareCommon(s.meal,s.m,JSON.stringify(s.common));for(let i=0;i<5;i++)await uploadPart(s.meal,s.m,s.m.parts[i],[s.records[i]],`2026-10-${String(i+1).padStart(2,'0')}T00:00:00Z`);}
const egg=(code:string,ore:number)=>normalize({code,name:'Ägg 6p Frigående Medium',priceValue:ore/100,priceUnit:'kr/st',displayVolume:'6p',online:true,outOfStock:false,addToCartDisabled:false,potentialPromotions:[]},'Mejeri, ost & ägg',new Date().toISOString());
async function link(s:ReturnType<typeof setup>,items:Entry[]=[egg('EGG_A',1800)]){const scan:Scan={entries:items,store:{storeId:'2110',name:'Test',onlineStore:true},categories:[],requests:0,startedAt:new Date().toISOString(),completedAt:new Date().toISOString()};await publish(s.catalog,scan);await refreshIngredientLinks(s.catalog,await loadCloudRequirements(s.meal));}
const req=(path:string,body?:any,secret=readToken)=>new Request('https://example.test'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const env=(s:ReturnType<typeof setup>)=>({DB:binding(s.catalog),MEAL_DB:binding(s.meal),CATALOG_API_TOKEN:readToken});
test('release checksums reject corrupt compressed assets',()=>{const b=gzipSync('hello'),a={file:'x',bytes:b.length,uncompressedBytes:5,sha256:digest(b)};assert.equal(unpackAsset(b,a),'hello');assert.throws(()=>unpackAsset(gzipSync('world'),a),/checksum/);});
test('import exposes no partial recipes and only one completed part per UTC day',async()=>{const s=setup();try{await prepareCommon(s.meal,s.m,JSON.stringify(s.common));const inventory=await loadCloudRequirements(s.meal);assert.equal(inventory.requirements.length,2);assert.equal(inventory.inventorySource,'cloud-recipe-database');assert.equal((await handle(req('/meal/recipes'),env(s))).status,503);await uploadPart(s.meal,s.m,s.m.parts[0],[s.records[0]],'2026-10-07T10:00:00Z');assert.equal((await nextImportPart(s.meal,s.m,'2026-10-07')).waitingForNextDay,true);assert.equal((await nextImportPart(s.meal,s.m,'2026-10-08')).part?.day,2);assert.equal((await(await handle(req('/meal/status'),env(s))).json() as any).uploadedRecipes,1);}finally{s.meal.close();s.catalog.close();}});
test('interrupted import resumes insert-once documents and refuses corrupted stored documents',async()=>{const s=setup();try{await prepareCommon(s.meal,s.m,JSON.stringify(s.common));await s.meal.query('INSERT INTO meal_recipes VALUES(?,?,?,?,?,?,?)',[s.m.datasetId,1,s.records[0].name,s.records[0].names,s.records[0].summary,s.records[0].document,s.records[0].hash]);await uploadPart(s.meal,s.m,s.m.parts[0],[s.records[0]]);assert.equal((await rows(s.meal,'SELECT COUNT(*) AS n FROM meal_recipes'))[0].n,1);const bad={...s.records[1],hash:'wrong'};await assert.rejects(uploadPart(s.meal,s.m,s.m.parts[1],[bad]),/Invalid recipe/);}finally{s.meal.close();s.catalog.close();}});
test('cloud inventory detects missing subjects and never falls back to legacy requirements',async()=>{const s=setup();try{await assert.rejects(loadCloudRequirements(s.meal),/no legacy/);await prepareCommon(s.meal,s.m,JSON.stringify(s.common));await s.meal.query("DELETE FROM meal_ingredients WHERE ingredient_name='eggs'");await assert.rejects(loadCloudRequirements(s.meal),/integrity/);}finally{s.meal.close();s.catalog.close();}});
test('meal API authenticates, filters strict unknowns, supports OR cuisines and pins cursor filters',async()=>{const s=setup();try{await complete(s);await link(s);assert.equal((await handle(req('/meal/status',undefined,'wrong'),env(s))).status,401);const search=async(p:string)=>(await(await handle(req(p),env(s))).json()) as any;assert.deepEqual((await search('/meal/recipes?diet=vegetarian&excludeAllergen=milk')).recipes.map((r:any)=>r.id),[1,4,5]);assert.deepEqual((await search('/meal/recipes?cuisine=mexican,nordic&nutrition=protein_ge_20g')).recipes.map((r:any)=>r.id),[1,4]);const page=await search('/meal/recipes?limit=2');assert.deepEqual(page.recipes.map((r:any)=>r.id),[1,2]);const next=await search('/meal/recipes?limit=2&cursor='+encodeURIComponent(page.nextCursor));assert.deepEqual(next.recipes.map((r:any)=>r.id),[3,4]);assert.equal((await handle(req('/meal/recipes?diet=vegetarian&cursor='+encodeURIComponent(page.nextCursor)),env(s))).status,409);assert.equal((await handle(req('/meal/recipes?diet=wrong'),env(s))).status,400);const detail=await search('/meal/recipes/1');assert.equal(detail.ingredients[0].connection.willysItemId,'EGG_A');assert.equal(detail.profile.nutrition_metrics.nutrients_per_serving.Calories,100);assert.equal((await search('/meal/recipes/1/reviews')).reviews.length,1);assert.equal((await search('/meal/recipes/1/archive')).reviews[0].Review,'Review 1');}finally{s.meal.close();s.catalog.close();}});
test('quotes scale quantities, aggregate packs once and follow current replacement IDs and prices',async()=>{const s=setup();try{await complete(s);await link(s);const get=async(body:any)=>(await(await handle(req('/meal/quote',body),env(s))).json()) as any;const q=await get({recipes:[{recipeId:1,servings:4},{recipeId:2}]});assert.equal(q.complete,true);assert.equal(q.consumedCostOre,2700);assert.equal(q.purchaseCostOre,3600);assert.equal(q.shoppingList[0].packs,2);assert.equal(q.recipes[0].nutritionPerServing.Calories,100);await link(s,[egg('EGG_B',1200)]);const replacement=await get({recipes:[{recipeId:1}]});assert.equal(replacement.shoppingList[0].willysItemId,'EGG_B');assert.equal(replacement.consumedCostOre,600);assert.equal((await rows(s.catalog,'SELECT COUNT(*) AS n FROM ingredient_links'))[0].n,4);const lookup=await(await handle(req('/meal/ingredients/lookup',{names:['eggs','unused legacy food']}),env(s))).json() as any;assert.equal(lookup.ingredients[1].status,'unknown_ingredient');}finally{s.meal.close();s.catalog.close();}});
test('catalogue/connection lag fails quotes closed and unavailable products disappear from default search',async()=>{const s=setup();try{await complete(s);await link(s);await s.catalog.query("UPDATE catalog_entries SET data_json=json_set(data_json,'$.available',0)");assert.equal((await(await handle(req('/meal/recipes'),env(s))).json() as any).recipes.length,0);assert.equal((await(await handle(req('/meal/recipes?availableOnly=false'),env(s))).json() as any).recipes.length,5);await s.catalog.query("UPDATE ingredient_runs SET catalogue_snapshot_id='changed'");assert.equal((await handle(req('/meal/quote',{recipes:[{recipeId:1}]}),env(s))).status,503);}finally{s.meal.close();s.catalog.close();}});
test('unknown, conflicting, density and piece-weight amounts remain unresolved; valid explicit overrides work',()=>{const product={code:'A',name:'Food',brand:null,priceOre:2000,priceUnit:'kr/st',depositOre:0,available:true,observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+1000000).toISOString(),pack:{quantity:500,unit:'g',approximate:false,drainedGrams:null}};const i={ingredient_original:'rice',unit:'cup',measured_quantity:'1/2'};assert.equal(calculateLine(i,product,'matched',1).reason,'density_required');assert.equal(calculateLine({...i,unit:'count'},product,'matched',1).reason,'piece_weight_required');assert.equal(calculateLine({...i,measured_quantity:null},product,'matched',1).consumedCostOre,null);assert.equal(calculateLine({...i,unit:'g',quantity_conflict:1},product,'matched',1).reason,'conflicting_source_quantity');assert.equal(calculateLine(i,product,'matched',2,{unit:'g',quantity:125}).consumedCostOre,1000);assert.equal(canonicalAmount({...i,unit:'fluid_ounce',measured_quantity:'1'}).amount?.quantity,29.5735295625);assert.equal(aggregateShopping([calculateLine(i,product,'matched',1,{unit:'g',quantity:125}),calculateLine(i,product,'matched',1,{unit:'g',quantity:125})])[0].packs,1);});
test('completed import verifies all ingredient and review counts before activation',async()=>{const s=setup();try{await prepareCommon(s.meal,s.m,JSON.stringify(s.common));for(let i=0;i<4;i++)await uploadPart(s.meal,s.m,s.m.parts[i],[s.records[i]]);await assert.rejects(uploadPart(s.meal,{...s.m,reviews:6},s.m.parts[4],[s.records[4]]),/review count/);assert.equal((await rows(s.meal,"SELECT value FROM meal_meta WHERE key='ready'")).length,0);await uploadPart(s.meal,s.m,s.m.parts[4],[s.records[4]]);assert.equal((await nextImportPart(s.meal,s.m)).complete,true);}finally{s.meal.close();s.catalog.close();}});

test('fixed-price drained packages cannot silently use gross weight as edible weight',()=>{const p={code:'CAN',name:'Beans',brand:null,priceOre:1200,priceUnit:'kr/st',depositOre:0,available:true,observedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+100000).toISOString(),pack:{quantity:400,unit:'g',approximate:false,drainedGrams:240}};assert.equal(calculateLine({ingredient_original:'canned beans',unit:'g',measured_quantity:'240'},p,'matched',1).reason,'drained_weight_basis_requires_review');});

test('ingredient archive preserves original evidence and current pagination omits historical price objects',async()=>{const s=setup();try{await complete(s);await link(s);await s.meal.query("UPDATE meal_ingredients SET document_json=json_set(document_json,'$.sourceConnection',json(?)) WHERE ingredient_name='eggs'",[JSON.stringify({status:'matched',willys_item_id:'OLD_ARCHIVE_ID'})]);const archive=await(await handle(req('/meal/ingredients/archive?name=eggs'),env(s))).json() as any;assert.equal(archive.sourceConnection.willys_item_id,'OLD_ARCHIVE_ID');const current=await(await handle(req('/meal/ingredients/lookup',{names:['eggs']}),env(s))).json() as any;assert.equal(current.ingredients[0].connection.willysItemId,'EGG_A');assert.equal(current.ingredients[0].sourceConnection,undefined);}finally{s.meal.close();s.catalog.close();}});
