import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';
import { DIETARY_POLICY_VERSION, evaluateIngredientPolicyUncached, normalizePolicyTextUncached } from '../src/dietary-policy.ts';

type CoopDataset = {
  connections: Array<{ name: string; approvedProducts: Array<{ productId: string }> }>;
  observations: Array<{ product: { id: string; name: string; brand: string | null; categories: string[]; ingredientsText: string | null } }>;
};
type ClassificationRow = readonly [string, string | null, 'chicken' | 'red_meat' | 'other_meat' | null];
export type PolicySeedData = {
  version: string;
  policySourceSha256: string;
  identitySourceSha256: string;
  datasetSha256: string;
  inputCount: number;
  textRows: Array<readonly [string, string]>;
  classificationRows: ClassificationRow[];
};

const MAX_INPUT_LENGTH = 4096;
const MAX_SEED_INPUTS = 4096;
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const datasetPath = resolve(root, 'data/coop-reviewed-dataset-20261009.json');
const policyPath = resolve(root, 'src/dietary-policy.ts');
const identityPath = resolve(root, 'src/retailers/identity.ts');
const outputPath = resolve(root, 'src/dietary-policy-seed.ts');

function addInput(set: Set<string>, value: unknown): void {
  if (typeof value === 'string' && value.length > 0 && value.length <= MAX_INPUT_LENGTH) set.add(value);
}

function disclosedPolicyInput(text: string): string {
  const normalized = text.normalize('NFKD').replace(/\p{M}/gu, '').toLowerCase();
  const eggOnlyHenWording = /\b(?:egg|eggs|egg yolk|agg|aggula|aeg)\b/.test(normalized)
    && !/\b(?:chicken|kyckling\w*|poultry|h[oö]n(?:s)?k[oö]tt)\b/.test(normalized);
  return eggOnlyHenWording ? normalized.replace(/\b(?:hons|hens?)\b/g, ' ') : text;
}

export function buildPolicySeedData(dataset: CoopDataset, policySource: string, identitySource: string, datasetSource: string): PolicySeedData {
  const tracked = new Set(dataset.connections.flatMap(connection => connection.approvedProducts.map(product => product.productId)));
  const products = new Map<string, CoopDataset['observations'][number]['product']>();
  for (const observation of dataset.observations) {
    if (tracked.has(observation.product.id)) products.set(observation.product.id, observation.product);
  }

  const textInputs = new Set<string>();
  const classificationInputs = new Set<string>();
  for (const connection of dataset.connections) {
    addInput(textInputs, connection.name);
    addInput(classificationInputs, connection.name);
  }
  for (const product of products.values()) {
    addInput(textInputs, product.name);
    addInput(classificationInputs, product.name);
    addInput(textInputs, product.brand);
    for (const category of product.categories ?? []) addInput(textInputs, category);
    if (product.ingredientsText) {
      addInput(textInputs, product.ingredientsText);
      const policyInput = disclosedPolicyInput(product.ingredientsText);
      addInput(textInputs, policyInput);
      addInput(classificationInputs, policyInput);
    }
  }

  const allInputs = new Set([...textInputs, ...classificationInputs]);
  if (allInputs.size > MAX_SEED_INPUTS) throw new Error(`policy_seed_input_limit_exceeded:${allInputs.size}`);
  const textRows = [...textInputs].sort().map(input => [input, normalizePolicyTextUncached(input)] as const);
  const classificationRows: ClassificationRow[] = [...classificationInputs].sort().map(input => {
    const result = evaluateIngredientPolicyUncached(input);
    return [input, result.blockedReason, result.meat] as const;
  });
  return {
    version: DIETARY_POLICY_VERSION,
    policySourceSha256: createHash('sha256').update(policySource).digest('hex'),
    identitySourceSha256: createHash('sha256').update(identitySource).digest('hex'),
    datasetSha256: createHash('sha256').update(datasetSource).digest('hex'),
    inputCount: allInputs.size,
    textRows,
    classificationRows,
  };
}

export function renderPolicySeedModule(seed: PolicySeedData): string {
  return `// Generated by scripts/generate-policy-seed.ts. Do not edit by hand.\n`
    + `export const POLICY_SEED_VERSION = ${JSON.stringify(seed.version)};\n`
    + `export const POLICY_SEED_SOURCE_SHA256 = ${JSON.stringify(seed.policySourceSha256)};\n`
    + `export const POLICY_SEED_IDENTITY_SHA256 = ${JSON.stringify(seed.identitySourceSha256)};\n`
    + `export const POLICY_SEED_DATA_SHA256 = ${JSON.stringify(seed.datasetSha256)};\n`
    + `export const POLICY_SEED_INPUT_COUNT = ${seed.inputCount};\n`
    + `export const POLICY_TEXT_SEED: readonly (readonly [string, string])[] = ${JSON.stringify(seed.textRows)};\n`
    + `export const INGREDIENT_POLICY_SEED: readonly (readonly [string, string | null, 'chicken' | 'red_meat' | 'other_meat' | null])[] = ${JSON.stringify(seed.classificationRows)};\n`;
}

export function generatePolicySeed(inputPath=datasetPath,generatedPath=outputPath): PolicySeedData {
  const datasetSource = readFileSync(inputPath, 'utf8');
  const policySource = readFileSync(policyPath, 'utf8');
  const identitySource = readFileSync(identityPath, 'utf8');
  const dataset = JSON.parse(datasetSource) as CoopDataset;
  const seed = buildPolicySeedData(dataset, policySource, identitySource, datasetSource);
  writeFileSync(generatedPath, renderPolicySeedModule(seed));
  return seed;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const {values}=parseArgs({options:{input:{type:'string'},output:{type:'string'}}});
  const seed = generatePolicySeed(values.input?resolve(values.input):datasetPath,values.output?resolve(values.output):outputPath);
  console.log(JSON.stringify({ inputCount: seed.inputCount, policyTextCount: seed.textRows.length,
    classificationCount: seed.classificationRows.length, version: seed.version,
    sourceFingerprint: seed.policySourceSha256, identityFingerprint: seed.identitySourceSha256,
    datasetFingerprint: seed.datasetSha256 }));
}
