export function mealOpenApi(origin:string){
  const response={description:'JSON response; complete schemas and examples are documented in docs/mealplanner-api.md',content:{'application/json':{schema:{type:'object'}}}};
  const read=(description:string,parameters:any[]=[])=>({get:{summary:description,parameters,responses:{'200':response,'400':{description:'Invalid parameter'},'401':{description:'Bearer token missing/incorrect'},'404':{description:'Not found'},'409':{description:'Cursor/version mismatch'},'503':{description:'Import or current connections not ready'}}}});
  const parameter=(name:string,schema:any,description:string)=>({name,in:'query',schema,description});
  const pathId={name:'recipeId',in:'path',required:true,schema:{type:'integer',minimum:1}};
  const limit=parameter('limit',{type:'integer',minimum:1,maximum:100,default:20},'Page size');
  const cursor=parameter('cursor',{type:'string'},'Opaque cursor; preserve all filters when paging');
  const searchParameters=[limit,cursor,parameter('candidateProfile',{type:'string',maxLength:4000},'JSON v1 {version:1,calories,targets:{protein:{min:70},fiber:{min:22}},trackedNutrients:[...]}; ranks all strict matches by nutrient density before pagination; targets are advisory, not independent guarantees'),parameter('planningSlot',{type:'string',enum:['breakfast','lunch','dinner','snack','dessert']},'Optional planning slot; applies the versioned exact-ID curation for known test/component source records'),parameter('q',{type:'string',maxLength:100},'Recipe title substring, maximum 100 UTF-8 bytes'),...['diet','excludeAllergen','cuisine','region','mealType','taste','nutrition'].map(name=>parameter(name,{type:'string'},'Comma-separated filter keys from /meal/filters')),parameter('availableOnly',{type:'boolean',default:true},'Only recipes with currently available connections')];
  return {openapi:'3.1.0',info:{title:'Willys Meal Planner API',version:'1.0.0',description:'Retained recipes, ingredient quantities/evidence, multi-state filters, nutrition, reviews, current approved product IDs and live prices. Values in öre. Unknown costs are explicit.'},servers:[{url:origin}],security:[{bearerAuth:[]}],
    components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer'}},schemas:{RecipeSelection:{type:'object',required:['recipeId'],properties:{recipeId:{type:'integer',minimum:1},servings:{type:'number',exclusiveMinimum:0,maximum:1000},amountOverrides:{type:'object',description:'Ingredient-index keys. Amounts refer to the original whole recipe before scaling.',additionalProperties:{type:'object',required:['unit','quantity'],properties:{unit:{enum:['g','ml','piece']},quantity:{type:'number',exclusiveMinimum:0,maximum:10000000}}}}}}}},
    paths:{'/meal/status':read('Import progress and current dataset/catalogue/connection versions'),'/meal/dataset':read('Release manifest, complete source metadata, classifier provenance and GitHub database archive'),'/meal/filters':read('All filter definitions in Swedish and English'),'/meal/recipes':read('Search and filter recipes',searchParameters),'/meal/recipes/{recipeId}':read('Recipe source, quantities, filter evidence, nutrition and current product links',[pathId]),'/meal/recipes/{recipeId}/archive':read('Exact exported recipe document including all retained reviews and source/evidence fields',[pathId]),'/meal/recipes/{recipeId}/reviews':read('Paginated retained reviews',[pathId,limit,parameter('offset',{type:'integer',minimum:0,default:0},'Review offset')]),'/meal/recipes/{recipeId}/cost':read('Recipe cost quote and shopping list',[pathId,parameter('servings',{type:'number',exclusiveMinimum:0},'Requested portions; omit for original whole recipe')]),'/meal/quote':{post:{summary:'Price up to 32 recipe selections and aggregate their shopping list',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['recipes'],properties:{recipes:{type:'array',minItems:1,maxItems:32,items:{$ref:'#/components/schemas/RecipeSelection'}}}}}}},responses:{'200':response,'400':{description:'Invalid selection/override'},'401':{description:'Unauthorized'},'404':{description:'Recipe missing'},'422':{description:'Requested scaling but source serving count is unknown'},'503':{description:'Current cloud connections not ready'}}}},'/meal/ingredients/archive':read('Complete retained ingredient evidence including original historical connection',[parameter('name',{type:'string'},'Exact retained ingredient name')]),'/meal/ingredients':read('Ingredient classification and current approved products',[limit,cursor]),'/meal/ingredients/lookup':{post:{summary:'Look up up to 100 exact retained ingredient names',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['names'],properties:{names:{type:'array',maxItems:100,items:{type:'string',maxLength:1000}}}}}}},responses:{'200':response}}},'/status':read('Current retailer catalogue status'),'/products/{code}':read('Current product including pack pricing',[{name:'code',in:'path',required:true,schema:{type:'string'}}]),'/history/{code}':read('Recorded price changes',[{name:'code',in:'path',required:true,schema:{type:'string'}}])}};
}
