// Product identity rules. Prices never override a food mismatch. Keep English
// aliases separate from Swedish retail title patterns and preserve preparation.
export type FoodRule = { id: string; aliases: string[]; title: string; categories: string[];
  exclude?: string; basis: 'kg' | 'l' | 'piece'; ambiguous?: boolean; form?: 'fresh' | 'dried' };
const rules: FoodRule[] = [];
function food(id: string, aliases: string, title: string, categories: string, basis: FoodRule['basis'] = 'kg',
  extra: Partial<FoodRule> = {}) {
  rules.push({ id, aliases: aliases.split('|'), title, categories: categories.split('|'), basis, ...extra });
}
const shelf = 'skafferi', dairy = 'mejeri', produce = 'frukt', meat = 'kott', frozen = 'fryst', fish = 'fisk';
food('salt','salt|table salt|iodized salt','^(?:fint )?salt\\b|^bordssalt',shelf);
food('sea-salt','sea salt|fine sea salt','havssalt|flingsalt.*(?:naturell|jod)',shelf);
food('kosher-salt','kosher salt|coarse salt','kosher|^grovt salt',shelf,'kg',{ambiguous:true});
food('butter','butter','^smor\\b',dairy,'kg',{exclude:'vitlok|persilja|flytande|margarin|smorgas|extra.*salt'});
food('unsalted-butter','unsalted butter|sweet butter','^smor osaltat',dairy);
food('salted-butter','salted butter','^smor normalsaltat',dairy);
food('margarine','margarine|oleo','margarin|^smorgas vaxtbaserat',dairy,'kg',{exclude:'flytande|olja'});
food('sugar','sugar|white sugar|granulated sugar|white granulated sugar|caster sugar|superfine sugar','^strosocker|^finkornigt strosocker',shelf);
food('brown-sugar','brown sugar|light brown sugar|dark brown sugar|packed brown sugar','^farinsocker|^brun farin',shelf);
food('powdered-sugar',"powdered sugar|confectioners sugar|confectioners' sugar|icing sugar",'^florsocker',shelf);
food('egg','egg|eggs|whole egg|whole eggs|large eggs|large egg','^(?:bruna )?(?:frukost)?agg\\b',dairy,'piece');
food('egg-white','egg white|egg whites','^aggvita',dairy,'kg');
food('onion','onion|onions|yellow onion|yellow onions','^(?:lok gul|gul lok)',produce);
food('red-onion','red onion|red onions','^(?:lok rod|rod lok)',produce);
food('white-onion','white onion|white onions','^(?:lok vit|vit lok)',produce);
food('green-onion','green onion|green onions|scallion|scallions|spring onion|spring onions','salladslok',produce);
food('shallot','shallot|shallots','schalottenlok',produce);
food('garlic','garlic|garlic clove|garlic cloves|cloves of garlic','^vitlok\\b',produce);
food('garlic-powder','garlic powder|granulated garlic','^vitlokspulver|^vitlok (?:pulver|granulerad)',shelf);
food('garlic-salt','garlic salt','^vitlokssalt',shelf);
food('onion-powder','onion powder','^lokpulver|^lok pulver',shelf);
food('flour','flour|all-purpose flour|all purpose flour|plain flour|white flour|unbleached flour','^vetemjol(?:\\s|$)',shelf,'kg',{exclude:'special|fullkorn'});
food('bread-flour','bread flour|strong flour','^vetemjol special',shelf);
food('whole-wheat-flour','whole wheat flour|whole-wheat flour|wholemeal flour|graham flour','^grahamsmjol|^vetemjol fullkorn',shelf);
food('rye-flour','rye flour','^ragmjol',shelf);
food('rice-flour','rice flour','^rismjol',shelf);
food('cornstarch','cornstarch|corn starch','^majsstarkelse',shelf);
food('cornmeal','cornmeal|corn meal|maize flour','^majsmjol|^polenta',shelf);
food('potato-starch','potato starch|potato flour','^potatismjol',shelf);
food('almond-flour','almond flour|almond meal|ground almonds','^mandelmjol',shelf);
food('oat-flour','oat flour','^havremjol',shelf);
food('buckwheat-flour','buckwheat flour','^bovetemjol',shelf);
food('semolina','semolina|semolina flour','^mannagryn|^durumvetemjol',shelf,'kg',{ambiguous:true});
food('baking-powder','baking powder','^bakpulver',shelf);
food('baking-soda','baking soda|bicarbonate of soda|sodium bicarbonate','^bikarbonat',shelf);
food('dry-yeast','active dry yeast|dry yeast|instant yeast|instant dry yeast|rapid rise yeast','^torrjast',shelf);
food('fresh-yeast','fresh yeast|compressed yeast','^jast\\b',dairy);
food('olive-oil','olive oil|extra virgin olive oil|extra-virgin olive oil','^olivolja',shelf,'l');
food('canola-oil','canola oil|rapeseed oil','^rapsolja',shelf,'l',{exclude:'smor|oliv|smak'});
food('sunflower-oil','sunflower oil','^solrosolja',shelf,'l');
food('vegetable-oil','vegetable oil|oil|cooking oil','^(?:rapsolja|solrosolja)',shelf,'l',{ambiguous:true});
food('sesame-oil','sesame oil','^sesamolja',shelf,'l');
food('peanut-oil','peanut oil|groundnut oil','^jordnotsolja',shelf,'l');
food('coconut-oil','coconut oil','^kokosolja',shelf,'kg');
food('milk','milk','^(?:standardmjolk|mellanmjolk|lattmjolk|mjolk)(?:\\b| )',dairy,'l',{exclude:'pulver|choklad|kondenserad|smak|protein|ris|havre'});
food('whole-milk','whole milk|full-fat milk','^(?:standardmjolk|mjolk).*3%',dairy,'l');
food('skim-milk','skim milk|nonfat milk|fat-free milk|skimmed milk','^minimjolk',dairy,'l');
food('milk-2-percent','2% milk|2 percent milk','mjolk.*2%',dairy,'l');
food('milk-1-percent','1% milk|1 percent milk','mjolk.*1%',dairy,'l');
food('milk-powder','powdered milk|dry milk|milk powder|nonfat dry milk','^mjolkpulver',shelf);
food('condensed-milk','sweetened condensed milk|condensed milk','kondenserad mjolk.*sotad|sotad kondenserad mjolk',shelf,'kg',{exclude:'osotad|karamell'});
food('evaporated-milk','evaporated milk|unsweetened condensed milk','kondenserad mjolk osotad',shelf);
food('cream-heavy','heavy cream|heavy whipping cream|whipping cream|double cream','^vispgradd',dairy,'l',{exclude:'vanilj|spray|vaxt|latt'});
food('cream-light','light cream|single cream|half-and-half|half and half|half-and-half cream','^(?:matgradd|matlagnings.?gradd)',dairy,'l',{ambiguous:true});
food('sour-cream','sour cream','^graddfil',dairy,'l');
food('creme-fraiche','creme fraiche|crème fraîche|crème fraiche','^(?:creme fraiche|crème fraiche)',dairy,'l',{exclude:'smak|tomat|chili|vitlok|saffran'});
food('cream-cheese','cream cheese|philadelphia cream cheese','^original naturell.*farskost|^farskost naturell|^philadelphia.*naturell|^original.*farskost',dairy,'kg',{exclude:'vitlok|orter|light|vegan|latt'});
food('yogurt','plain yogurt|plain yoghurt|natural yogurt|yogurt|yoghurt','^naturell yoghurt|^yoghurt naturell',dairy,'kg',{exclude:'smak|vanilj|jordgubb|protein'});
food('greek-yogurt','greek yogurt|greek yoghurt|plain greek yogurt','grekisk yoghurt.*naturell|naturell grekisk|^grekisk yoghurt',dairy);
food('cottage-cheese','cottage cheese|small curd cottage cheese','^(?:keso|cottage cheese).*naturell|^cottage cheese',dairy,'kg',{exclude:'smak|ananas|mango|vanilj'});
food('ricotta','ricotta|ricotta cheese','^ricotta',dairy);
food('mascarpone','mascarpone|mascarpone cheese','^mascarpone',dairy);
food('parmesan','parmesan|parmesan cheese|parmigiano-reggiano cheese','parmesan|parmigiano reggiano',dairy,'kg',{exclude:'sauce|sas|pesto|kex'});
food('mozzarella','mozzarella|mozzarella cheese','^mozzarella',dairy,'kg',{exclude:'latt|light'});
food('cheddar','cheddar|cheddar cheese|sharp cheddar cheese|mild cheddar cheese','^cheddar',dairy,'kg',{exclude:'smalt|sauce|sas|vegan'});
food('feta','feta|feta cheese','^feta',dairy,'kg',{exclude:'sallad|sas|smak'});
food('gouda','gouda|gouda cheese','^gouda',dairy);
food('edam','edam|edam cheese','^edamer',dairy);
food('swiss-cheese','swiss cheese|emmental cheese|emmentaler','^emmental',dairy);
food('gruyere','gruyere|gruyere cheese|gruyère cheese','gruyere',dairy);
food('brie','brie|brie cheese','^brie',dairy);
food('blue-cheese','blue cheese|roquefort cheese','^adelost|^roquefort|^blamogelost',dairy);
food('gorgonzola','gorgonzola|gorgonzola cheese','^gorgonzola',dairy);
food('goat-cheese','goat cheese|goats cheese|chevre|chèvre','chevre|getost',dairy);
food('provolone','provolone|provolone cheese','provolone',dairy);
food('pepper-black','black pepper|ground black pepper|fresh ground black pepper|pepper','^svartpeppar',shelf,'kg',{exclude:'hel|kvarn|mix'});
food('peppercorns','black peppercorns|peppercorns','^svartpeppar hel',shelf);
food('pepper-white','white pepper|ground white pepper','^vitpeppar',shelf,'kg',{exclude:'hel|kvarn'});
food('cinnamon','cinnamon|ground cinnamon','^kanel',shelf,'kg',{exclude:'hel|stang|socker|kvarn'});
food('cinnamon-stick','cinnamon stick|cinnamon sticks','^kanel hel|kanelstang',shelf);
food('paprika','paprika|sweet paprika|ground paprika','^paprikapulver',shelf);
food('smoked-paprika','smoked paprika','^paprikapulver.*rokt|^rokt paprika',shelf);
food('cayenne','cayenne pepper|ground cayenne pepper|cayenne','^cayenne',shelf);
food('cumin','cumin|ground cumin','^spiskummin',shelf,'kg',{exclude:'hel'});
food('nutmeg','nutmeg|ground nutmeg','^muskot.*malen|^muskotnot malen',shelf);
food('ginger-dried','ground ginger|ginger powder','^ingefara',shelf,'kg',{exclude:'syltad|inlagd|dryck'});
food('ginger-fresh','ginger|fresh ginger|gingerroot|fresh gingerroot|ginger root','^ingefara',produce);
food('cloves-dried','ground cloves','^kryddnejlika.*malen',shelf);
food('cloves-whole','cloves|whole cloves','^kryddnejlika.*hel',shelf);
food('allspice','allspice|ground allspice','^kryddpeppar',shelf,'kg',{exclude:'hel'});
food('turmeric','turmeric|ground turmeric','^gurkmeja',shelf);
food('coriander-dried','ground coriander|coriander seed|coriander seeds|ground coriander seeds','^koriander',shelf);
food('cardamom','cardamom|ground cardamom','^kardemumma',shelf,'kg',{exclude:'hel'});
food('chili-flakes','red pepper flakes|crushed red pepper flakes|crushed red pepper|chili flakes','chiliflakes|chili flakes',shelf);
food('chili-powder','chili powder','^chilipulver',shelf,'kg',{ambiguous:true});
food('curry','curry powder|curry','^curry',shelf,'kg',{exclude:'pasta|paste|sas|mix'});
food('bay-leaf','bay leaf|bay leaves','^lagerblad',shelf);
food('mustard-dry','dry mustard|mustard powder|ground mustard','senapspulver',shelf);
food('vanilla-extract','vanilla extract|pure vanilla extract','vaniljextrakt|vanilj extract',shelf,'l');
food('vanilla-bean','vanilla bean|vanilla beans|vanilla pod','vaniljstang',shelf,'piece');
food('vanilla-sugar','vanilla sugar','^vaniljsocker',shelf);
food('vanilla','vanilla','vaniljextrakt|vaniljsocker',shelf,'kg',{ambiguous:true});
food('oregano-dried','oregano|dried oregano|dried oregano leaves','^oregano',shelf,'kg',{form:'dried'});
food('thyme-dried','thyme|dried thyme|dried thyme leaves','^timjan',shelf,'kg',{form:'dried'});
food('basil-dried','dried basil|dried basil leaves','^basilika',shelf,'kg',{form:'dried'});
food('parsley-dried','dried parsley|dried parsley flakes','^persilja',shelf,'kg',{form:'dried'});
food('rosemary-dried','dried rosemary|rosemary','^rosmarin',shelf,'kg',{form:'dried'});
food('sage-dried','dried sage|ground sage|sage','^salvia',shelf,'kg',{form:'dried'});
food('tarragon-dried','dried tarragon|tarragon','^dragon',shelf,'kg',{form:'dried'});
food('dill-dried','dried dill|dill weed','^dill',shelf,'kg',{form:'dried'});
food('parsley-fresh','fresh parsley|flat leaf parsley|flat-leaf parsley|italian parsley','^(?:blad)?persilja',produce,'kg',{form:'fresh'});
food('basil-fresh','fresh basil|fresh basil leaves','^basilika',produce,'kg',{form:'fresh'});
food('cilantro-fresh','cilantro|fresh cilantro|fresh coriander|coriander leaves','^koriander',produce,'kg',{form:'fresh'});
food('dill-fresh','fresh dill','^dill',produce,'kg',{form:'fresh'});
food('mint-fresh','fresh mint|fresh mint leaves','^mynta',produce,'kg',{form:'fresh'});
food('thyme-fresh','fresh thyme','^timjan',produce,'kg',{form:'fresh'});
food('rosemary-fresh','fresh rosemary','^rosmarin',produce,'kg',{form:'fresh'});
food('chives','chives|fresh chives','graslok',produce,'kg',{form:'fresh'});
food('parsley-unspecified','parsley','^(?:blad)?persilja',produce+'|'+shelf,'kg',{ambiguous:true});
food('basil-unspecified','basil','^basilika',produce+'|'+shelf,'kg',{ambiguous:true});
food('honey','honey|liquid honey','^honung',shelf);
food('maple-syrup','maple syrup|pure maple syrup','lonnsirap|maple syrup',shelf,'kg');
food('molasses','molasses|blackstrap molasses','melass',shelf);
food('golden-syrup','golden syrup|light syrup','^ljus sirap',shelf);
food('corn-syrup','corn syrup|light corn syrup|dark corn syrup','corn syrup|majssirap',shelf);
food('agave','agave nectar|agave syrup','agavesirap',shelf);
food('peanut-butter','peanut butter|creamy peanut butter|smooth peanut butter','^jordnotssmor',shelf,'kg',{exclude:'crunch|chunk'});
food('peanut-butter-crunchy','chunky peanut butter|crunchy peanut butter','^jordnotssmor.*(?:crunch|chunk)',shelf);
food('tahini','tahini|sesame paste','^tahini|^sesampasta',shelf);
food('cocoa','cocoa|cocoa powder|unsweetened cocoa powder|unsweetened cocoa','^kakao',shelf,'kg',{exclude:'dryck|blandning'});
food('dark-chocolate','dark chocolate|bittersweet chocolate|semisweet chocolate|semi-sweet chocolate','^mork choklad|^choklad.*mork', 'glass|skafferi');
food('milk-chocolate','milk chocolate','^mjolkchoklad|^choklad.*mjolk','glass|skafferi');
food('white-chocolate','white chocolate','^vit choklad|^choklad.*vit','glass|skafferi');
food('chocolate-chips','chocolate chips|semi-sweet chocolate chips|semisweet chocolate chips','^chokladknappar.*mork|^chocolate chips',shelf);
food('coconut','shredded coconut|flaked coconut|desiccated coconut|unsweetened coconut|coconut flakes','^kokosflingor',shelf);
food('coconut-milk','coconut milk|unsweetened coconut milk','^kokosmjolk',shelf,'l',{exclude:'latt|light|dryck'});
food('coconut-cream','coconut cream','^kokosgradde',shelf,'l');
food('almond-milk','almond milk|unsweetened almond milk','^mandeldryck',dairy+'|dryck','l',{exclude:'vanilj|choklad'});
food('soy-milk','soy milk|soymilk|unsweetened soy milk','^sojadryck',dairy+'|dryck','l',{exclude:'vanilj|choklad'});
food('oat-milk','oat milk','^havredryck',dairy+'|dryck','l',{exclude:'vanilj|choklad'});
food('mayonnaise','mayonnaise|mayo','^(?:akta |real )?majonnas',shelf+'|'+dairy);
food('ketchup','ketchup|tomato ketchup','^tomatketchup|^ketchup',shelf);
food('dijon','dijon mustard','^dijon.*senap|^senap dijon',shelf);
food('mustard','prepared mustard|yellow mustard|mustard','^senap mild|^mild senap',shelf,'kg',{ambiguous:true});
food('soy-sauce','soy sauce|soya sauce','^(?:kinesisk |japansk )?soja\\b|^soy sauce',shelf,'l',{exclude:'sot|sweet|lag salt|mindre salt'});
food('soy-low-sodium','low sodium soy sauce|low-sodium soy sauce|reduced sodium soy sauce','soja.*(?:lag salt|mindre salt)',shelf,'l');
food('worcestershire','worcestershire sauce','worcestershire|worcester',shelf,'l');
food('fish-sauce','fish sauce|nam pla','^fisksas',shelf,'l');
food('oyster-sauce','oyster sauce','^ostronsas',shelf,'l');
food('hoisin','hoisin sauce','hoisin',shelf,'kg');
food('sriracha','sriracha|sriracha sauce','sriracha',shelf,'l',{exclude:'mayo|majonnas'});
food('hot-sauce','hot sauce|tabasco sauce|tabasco|hot pepper sauce','^tabasco|^hot sauce',shelf,'l');
food('bbq-sauce','barbecue sauce|bbq sauce|barbeque sauce','bbq.*sas|barbecue.*sauce',shelf);
food('salsa','salsa|salsa sauce','^salsa',shelf,'kg',{exclude:'verde'});
food('pesto','pesto|basil pesto','^pesto.*basil|^pesto genovese',shelf);
food('balsamic-vinegar','balsamic vinegar','balsamvinager',shelf,'l',{exclude:'crema|glaze'});
food('red-wine-vinegar','red wine vinegar','rodvinsvinager',shelf,'l');
food('white-wine-vinegar','white wine vinegar','vitvinsvinager',shelf,'l');
food('apple-vinegar','cider vinegar|apple cider vinegar','appelcidervinager',shelf,'l');
food('rice-vinegar','rice vinegar|rice wine vinegar','risvinager',shelf,'l');
food('white-vinegar','white vinegar|distilled white vinegar|vinegar','white vinegar|vitvinsvinager',shelf,'l',{ambiguous:true});
food('lemon-juice','lemon juice|bottled lemon juice','^citronjuice|^citron pressad',shelf+'|dryck','l');
food('lime-juice','lime juice|bottled lime juice','^limejuice|^lime pressad',shelf+'|dryck','l');
food('lemon','lemon|lemons','^citron\\b',produce,'kg',{exclude:'juice|gras'});
food('lime','lime|limes','^lime\\b',produce,'kg',{exclude:'juice'});
food('lemon-preparation','fresh lemon juice|lemon zest|lemon rind|lemon peel|grated lemon rind|grated lemon zest','^citron\\b',produce,'kg',{exclude:'juice|gras'});
food('lime-preparation','fresh lime juice|lime zest|lime rind|lime peel','^lime\\b',produce,'kg',{exclude:'juice'});
food('orange-preparation','orange zest|orange rind|orange peel|grated orange rind','^apelsin',produce);
food('orange','orange|oranges','^apelsin',produce,'kg',{exclude:'juice'});
food('orange-juice','orange juice|fresh orange juice','^apelsinjuice|^orange juice', 'dryck','l',{exclude:'bland|mango'});
food('tomato-fresh','tomato|tomatoes|fresh tomatoes','^(?:kvist)?tomat(?:er)?\\b|^plommontomat',produce,'kg',{exclude:'soltork|cocktail|korsbar|baby'});
food('tomato-cherry','cherry tomatoes|cherry tomato|grape tomatoes','korsbarstomat|cocktailtomat|babyplommon',produce);
food('tomato-canned','canned tomatoes|canned diced tomatoes|canned crushed tomatoes|crushed tomatoes|diced tomatoes','tomater (?:krossade|tarnade)|krossade tomater|tarnade tomater',shelf);
food('tomato-whole-canned','canned whole tomatoes|whole peeled tomatoes|peeled tomatoes','hela tomater skalade',shelf);
food('tomato-paste','tomato paste|tomato puree|tomato purée','^tomatpure',shelf);
food('tomato-sauce','tomato sauce','passerade tomater|^passata',shelf,'kg',{ambiguous:true});
food('tomato-dried','sun-dried tomatoes|sun dried tomatoes|sundried tomatoes','soltorkade tomater|tomater soltorkade|pomodori secchi',shelf+'|'+produce);
food('potato','potato|potatoes|white potatoes|baking potatoes|russet potatoes','^potatis\\b',produce,'kg',{exclude:'sot|farsk'});
food('potato-new','new potatoes|baby potatoes|small potatoes','^potatis.*(?:sma|delikatess|farsk)',produce);
food('sweet-potato','sweet potato|sweet potatoes|yams','^sotpotatis',produce);
food('carrot','carrot|carrots','^morot(?:ter)?\\b',produce);
food('celery','celery|celery stalk|celery stalks|celery ribs','blekselleri|stjalkselleri',produce);
food('celeriac','celeriac|celery root','rotselleri',produce);
food('zucchini','zucchini|courgette|courgettes','zucchini|squash',produce);
food('cucumber','cucumber|cucumbers','^gurka\\b',produce);
food('bell-pepper-red','red bell pepper|red bell peppers|red pepper','paprika rod|rod paprika',produce);
food('bell-pepper-green','green bell pepper|green bell peppers|green pepper','paprika gron|gron paprika',produce);
food('bell-pepper-yellow','yellow bell pepper|yellow bell peppers|yellow pepper','paprika gul|gul paprika',produce);
food('bell-pepper','bell pepper|bell peppers|sweet pepper|sweet peppers','^paprika',produce,'kg',{exclude:'chili'});
food('chili-fresh','chili pepper|chilli pepper|red chili|red chile|red chili pepper','^chili',produce);
food('jalapeno','jalapeno|jalapenos|jalapeño|jalapeños','jalapeno',produce);
food('jalapeno-pickled','pickled jalapenos|canned jalapeno peppers','jalapeno',shelf);
food('broccoli','broccoli|broccoli florets','^broccoli',produce);
food('cauliflower','cauliflower|cauliflower florets','^blomkal',produce);
food('cabbage','cabbage|green cabbage|white cabbage','^vitkal',produce);
food('cabbage-red','red cabbage','^rodkal',produce);
food('napa-cabbage','napa cabbage|chinese cabbage','salladskal|kinakal',produce);
food('kale','kale','^gronkal',produce);
food('spinach','spinach|fresh spinach|baby spinach','^spenat|^babyspenat',produce);
food('spinach-frozen','frozen spinach|frozen chopped spinach','spenat',frozen);
food('lettuce','lettuce|iceberg lettuce','isbergssallad',produce);
food('romaine','romaine lettuce|cos lettuce','romansallad',produce);
food('arugula','arugula|rocket','rucola|ruccola',produce);
food('mushroom','mushroom|mushrooms|fresh mushrooms|button mushrooms','champinjon',produce);
food('portobello','portabella mushrooms|portobello mushrooms|portobello mushroom','portabello|portobello',produce);
food('shiitake','shiitake mushrooms|shiitake','shiitake',produce);
food('eggplant','eggplant|aubergine','aubergine',produce);
food('asparagus','asparagus|fresh asparagus','sparris',produce);
food('leek','leek|leeks','purjolok',produce);
food('fennel','fennel|fennel bulb','^fankal',produce);
food('radish','radish|radishes','radisa|radisor',produce);
food('beet','beet|beets|beetroot','rodbeta',produce);
food('parsnip','parsnip|parsnips','palsternacka',produce);
food('turnip','turnip|turnips','majrova',produce);
food('rutabaga','rutabaga|swede','kalrot',produce);
food('avocado','avocado|avocados','avokado',produce);
food('pumpkin','pumpkin|fresh pumpkin','pumpa',produce);
food('butternut','butternut squash','butternut',produce);
food('peas-frozen','frozen peas|green peas|peas','^arter|^grona arter',frozen);
food('corn-frozen','frozen corn|frozen sweetcorn','^majs',frozen);
food('corn-canned','canned corn|whole kernel corn|sweet corn|corn kernels|sweetcorn','^majs',shelf,'kg',{exclude:'mjol|stark|pop'});
food('green-beans','green beans|french beans|string beans','haricots verts|grona bonor',produce+'|'+frozen);
food('banana','banana|bananas','^banan',produce);
food('apple','apple|apples','^apple',produce);
food('apple-granny','granny smith apple|granny smith apples','apple.*granny',produce);
food('pear','pear|pears','^paron',produce);
food('peach','peach|peaches','^persika',produce);
food('nectarine','nectarine|nectarines','^nektarin',produce);
food('plum','plum|plums','^plommon',produce);
food('pineapple','pineapple|fresh pineapple','^ananas',produce);
food('pineapple-canned','canned pineapple|crushed pineapple|pineapple chunks|pineapple tidbits','^ananas',shelf);
food('mango','mango|mangos|mangoes','^mango',produce);
food('kiwi','kiwi|kiwifruit','^kiwi',produce);
food('grape','grapes|red grapes|green grapes','vindruvor',produce);
food('grapefruit','grapefruit','grapefrukt',produce);
food('strawberry','strawberry|strawberries|fresh strawberries','jordgubbar',produce);
food('strawberry-frozen','frozen strawberries','jordgubbar',frozen);
food('raspberry','raspberries|fresh raspberries','hallon',produce);
food('raspberry-frozen','frozen raspberries','hallon',frozen);
food('blueberry','blueberries|fresh blueberries','blabar',produce);
food('blueberry-frozen','frozen blueberries','blabar',frozen);
food('cranberry-dried','dried cranberries','tranbar',shelf);
food('raisin','raisins|sultanas|golden raisins','^russin',shelf);
food('date','dates|pitted dates','dadlar',shelf+'|'+produce);
food('apricot-dried','dried apricots','aprikoser.*tork|torkade aprikoser',shelf);
food('prune','prunes|dried plums','katrinplommon',shelf);
food('walnut','walnuts|walnut|walnut pieces','^valnot',shelf);
food('pecan','pecans|pecan nuts|pecan halves','^pecan',shelf);
food('almond','almonds|almond|slivered almonds|sliced almonds','^mandel',shelf,'kg',{exclude:'mjol|massa|smor|dryck|godis'});
food('hazelnut','hazelnuts|hazelnut','^hasselnot',shelf);
food('cashew','cashews|cashew nuts|cashew','^cashew',shelf,'kg',{exclude:'salt|rosta|chili'});
food('peanut','peanuts|unsalted peanuts','^jordnot',shelf,'kg',{exclude:'smor|salt|rosta'});
food('peanut-salted','salted peanuts|roasted peanuts','^jordnot.*salt',shelf+'|glass');
food('pine-nut','pine nuts|pinenuts','^pinje',shelf);
food('pistachio','pistachios|pistachio nuts','^pistage',shelf);
food('sesame','sesame seeds|sesame seed','^sesamfro',shelf);
food('sunflower-seed','sunflower seeds|sunflower seed kernels','^solroskarn',shelf);
food('pumpkin-seed','pumpkin seeds|pepitas','^pumpakarn',shelf);
food('flax','flax seeds|flaxseed|linseed','^linfro',shelf);
food('chia','chia seeds','^chiafro',shelf);
food('poppy','poppy seeds|poppy seed','^vallmo',shelf);
food('oats','rolled oats|old fashioned oats|old-fashioned oats|oats|oatmeal|quick oats|quick-cooking oats','^havregryn',shelf,'kg',{exclude:'fiber'});
food('rice','rice|white rice|long grain rice|long-grain rice|uncooked rice|long-grain white rice','^ris langkorn|^langkornigt ris|^ris parboiled',shelf);
food('rice-basmati','basmati rice','basmatiris',shelf);
food('rice-jasmine','jasmine rice','jasminris',shelf);
food('rice-brown','brown rice|long-grain brown rice','råris|raris|fullkornsris',shelf);
food('rice-arborio','arborio rice|risotto rice','arborioris|risottoris',shelf);
food('quinoa','quinoa','^quinoa',shelf);
food('couscous','couscous','^couscous',shelf);
food('bulgur','bulgur','^bulgur',shelf);
food('barley','pearl barley|barley','korngryn',shelf);
food('lentil-red','red lentils','roda linser|linser roda',shelf);
food('lentil-green','lentils|green lentils|brown lentils','grona linser|linser grona',shelf);
food('chickpea','chickpeas|garbanzo beans|canned chickpeas','^kikartor',shelf);
food('black-bean','black beans|canned black beans','svarta bonor|bonor svarta',shelf);
food('kidney-bean','kidney beans|red kidney beans|canned kidney beans','kidneybonor',shelf);
food('white-bean','white beans|cannellini beans|navy beans|great northern beans','^vita bonor',shelf,'kg',{exclude:'tomat'});
food('pinto-bean','pinto beans','pintobonor',shelf);
food('spaghetti','spaghetti|spaghettini','^spaghetti',shelf);
food('penne','penne|penne pasta','^penne',shelf);
food('macaroni','macaroni|elbow macaroni','makaroner',shelf);
food('fettuccine','fettuccine|fettuccini|tagliatelle','fettuccine|tagliatelle',shelf);
food('lasagna','lasagna noodles|lasagne sheets|lasagna sheets','lasagneplattor',shelf);
food('pasta','pasta|dry pasta|uncooked pasta','^pasta\\b|^penne|^fusilli',shelf,'kg',{ambiguous:true});
food('rice-noodle','rice noodles|rice vermicelli','risnudlar',shelf);
food('egg-noodle','egg noodles','aggnudlar',shelf);
food('bread-white','white bread|sandwich bread','^rostbrod|^formfranska', 'brod');
food('bread-wholemeal','whole wheat bread|whole-wheat bread|wholemeal bread','^rostbrod.*fullkorn|^formbrod.*fullkorn','brod');
food('bread-crumbs','breadcrumbs|bread crumbs|dry breadcrumbs|dry bread crumbs','^strobrod',shelf);
food('panko','panko|panko breadcrumbs|panko bread crumbs','^panko',shelf);
food('tortilla-flour','flour tortillas|flour tortilla|wheat tortillas','^tortilla',shelf,'kg',{exclude:'majs|corn|chip'});
food('tortilla-corn','corn tortillas|corn tortilla','tortilla.*(?:majs|corn)',shelf,'kg',{exclude:'chip'});
food('tortilla-chip','tortilla chips','tortillachips','glass|skafferi');
food('puff-pastry','puff pastry|puff pastry sheets|frozen puff pastry','smordeg',dairy+'|'+frozen);
food('filo','phyllo dough|filo pastry|phyllo pastry','filodeg',frozen+'|'+dairy);
food('chicken-breast','chicken breasts|chicken breast|boneless skinless chicken breasts|boneless skinless chicken breast|boneless chicken breasts|chicken breast halves','kycklingfile',meat+'|'+frozen,'kg',{exclude:'lår|lar|grill|tillagad|krydd|marinerad|panerad|fardig'});
food('chicken-thigh','chicken thighs|boneless chicken thighs','kycklinglar',meat+'|'+frozen,'kg',{exclude:'grill|tillagad|krydd|marinerad'});
food('chicken-whole','whole chicken|whole chickens|roasting chicken','hel kyckling',meat+'|'+frozen);
food('chicken-wing','chicken wings','kycklingving',meat+'|'+frozen,'kg',{exclude:'grill|marinerad|krydd'});
food('chicken-mince','ground chicken|chicken mince','kycklingfars',meat);
food('beef-mince','ground beef|beef mince|lean ground beef|hamburger','^notfars',meat+'|'+frozen);
food('pork-mince','ground pork|pork mince','^flaskfars',meat);
food('lamb-mince','ground lamb|lamb mince','^lammfars',meat);
food('turkey-mince','ground turkey|turkey mince','kalkonfars',meat);
food('pork-tenderloin','pork tenderloin|pork fillet','flaskfile',meat);
food('pork-chop','pork chops|pork chop','flaskkotlett',meat);
food('beef-tenderloin','beef tenderloin|filet mignon','oxfile',meat);
food('sirloin','sirloin steak|beef sirloin|sirloin','ryggbiff',meat);
food('ribeye','ribeye steak|rib-eye steak|rib eye steak','entrecote',meat);
food('beef-stew','stewing beef|beef stew meat|beef chuck','grytbitar.*not|hogrev',meat);
food('bacon','bacon|bacon slices|streaky bacon','^bacon|^skivat bacon',meat,'kg',{exclude:'tarning|bits|kalkon|kyckling'});
food('ham','ham|cooked ham|deli ham','kokt skinka',meat);
food('prosciutto','prosciutto|parma ham','prosciutto|parmaskinka',meat);
food('salami','salami','salami',meat);
food('chorizo','chorizo|chorizo sausage','chorizo',meat);
food('pepperoni','pepperoni','pepperoni',meat);
food('salmon','salmon|salmon fillets|salmon fillet|fresh salmon','laxfile',fish+'|'+frozen,'kg',{exclude:'rokt|gravad|sas|marinerad|krydd'});
food('smoked-salmon','smoked salmon','kallrokt lax|lax kallrokt',fish);
food('cod','cod|cod fillets|cod fillet','torskfile',fish+'|'+frozen);
food('tuna-canned','canned tuna|tuna|tuna in water','tonfisk i vatten',shelf);
food('tuna-oil','tuna in oil','tonfisk i olja',shelf);
food('shrimp','shrimp|shrimps|prawns|peeled shrimp','skalade rakor|rakor skalade',fish+'|'+frozen);
food('anchovy','anchovy fillets|anchovies|anchovy','^sardeller',shelf+'|'+fish);
food('sardine','sardines','^sardiner',shelf);
food('mussel','mussels','musslor',fish+'|'+frozen);
food('tofu','tofu|firm tofu|extra firm tofu','^tofu.*naturell|^tofu natural', 'vegetariskt|mejeri');
food('chicken-stock','chicken broth|chicken stock|chicken bouillon','kycklingbuljong',shelf,'kg',{ambiguous:true});
food('beef-stock','beef broth|beef stock|beef bouillon','kottbuljong|oxbuljong',shelf,'kg',{ambiguous:true});
food('vegetable-stock','vegetable broth|vegetable stock|vegetable bouillon','gronsaksbuljong',shelf,'kg',{ambiguous:true});
food('chicken-bouillon-cube','chicken bouillon cube|chicken bouillon cubes','kycklingbuljong.*tarning',shelf);
food('beef-bouillon-cube','beef bouillon cube|beef bouillon cubes','kottbuljong.*tarning',shelf);
food('vegetable-bouillon-cube','vegetable bouillon cube|vegetable bouillon cubes','gronsaksbuljong.*tarning',shelf);
food('capers','capers|caper','^kapris',shelf);
food('olive-black','black olives|pitted black olives','oliver.*svarta|svarta oliver',shelf);
food('olive-green','green olives|pitted green olives','oliver.*grona|grona oliver',shelf);
food('pickle','dill pickles|pickles|dill pickle','saltgurka',shelf);
food('artichoke','artichoke hearts|canned artichoke hearts','kronartskock',shelf);
food('bamboo','bamboo shoots|canned bamboo shoots','bambuskott',shelf);
food('water-chestnut','water chestnuts|canned water chestnuts|sliced water chestnuts','vattenkastanj',shelf);
food('olive-kalamata','kalamata olives','kalamata',shelf);
food('jam-strawberry','strawberry jam|strawberry preserves','jordgubbssylt',shelf);
food('jam-raspberry','raspberry jam|raspberry preserves','hallonsylt',shelf);
food('marmalade','orange marmalade|marmalade','apelsinmarmelad',shelf);
food('applesauce','applesauce|unsweetened applesauce|apple sauce','appelmos',shelf);
food('vanilla-ice-cream','vanilla ice cream','vanilj.*graddglass|graddglass.*vanilj','glass');
food('marshmallow','marshmallows|miniature marshmallows|mini marshmallows','marshmallow','glass');
food('gelatine','gelatin|gelatine|unflavored gelatin|unflavoured gelatin','gelatin',shelf);
food('gelatine-leaves','gelatin sheets|gelatine leaves','gelatinblad',shelf);
food('almond-extract','almond extract','bittermandel.*arom|mandelarom',shelf,'l',{ambiguous:true});
food('baking-chocolate','unsweetened chocolate|baking chocolate|cooking chocolate','bakchoklad',shelf,'kg',{ambiguous:true});
food('raisins-currants','dried currants|currants','korinter',shelf);
food('fennel-seed','fennel seeds|fennel seed','fankalsfro',shelf);
food('caraway','caraway seeds|caraway seed','^kummin',shelf);
food('mustard-seed','mustard seeds|mustard seed','senapsfro',shelf);
food('saffron','saffron|saffron threads','saffran',shelf);
food('herbes-provence','herbes de provence|herbs de provence','herbes de provence|ortkryddor provencal',shelf);
food('italian-seasoning','italian seasoning|italian herbs','italiensk.*ort|ort.*italiensk',shelf,'kg',{ambiguous:true});
food('pumpkin-seed-oil','pumpkin seed oil','pumpafroolja',shelf,'l');
food('espresso','espresso powder|instant espresso powder','espresso.*snabb|snabb.*espresso','dryck|skafferi');
food('coffee-instant','instant coffee|instant coffee granules','snabbkaffe','dryck|skafferi');
food('coffee-ground','ground coffee|coffee grounds','bryggkaffe','dryck');
food('tea-black','black tea|tea bags|black tea bags','^svart te|^tea.*black','dryck');
food('beer','beer|lager beer','lager|pilsner','dryck','l',{exclude:'alkoholfri|lattol'});
food('baking-spray','cooking spray|nonstick cooking spray','cooking spray|matlagningsspray',shelf,'l');
food('shortening','shortening|vegetable shortening|crisco shortening','shortening|kokosfett',dairy+'|'+shelf,'kg',{ambiguous:true});
food('buttermilk','buttermilk','buttermilk|karnmjolk',dairy,'l');
food('cream-of-tartar','cream of tartar','cream of tartar|vinsten',shelf);
food('self-raising-flour','self-rising flour|self raising flour|self-raising flour','self raising|self rising',shelf);
food('white-wine','white wine|dry white wine','vitt matlagningsvin','dryck|skafferi','l',{ambiguous:true});
food('red-wine','red wine|dry red wine','rott matlagningsvin','dryck|skafferi','l',{ambiguous:true});
// Product-title spelling variants observed in the actual store catalogue.
const revise=(id:string,changes:Partial<FoodRule>)=>Object.assign(rules.find(r=>r.id===id)!,changes);
revise('butter',{exclude:'vitlok|persilja|flytande|margarin|smorgas|extra.*salt|raps|olja'});
revise('cream-cheese',{title:'^naturell farskost|^original naturell.*farskost|^farskost naturell',exclude:'light|latt|vegan|getost'});
revise('celery',{title:'^bladselleri|^blekselleri|^stjalkselleri',aliases:['celery','celery stalk','celery stalks','celery ribs']});
revise('shallot',{title:'schalotten|bananschalotten'});
for(const id of ['walnut','pecan','almond','hazelnut','cashew','peanut','pine-nut','pistachio']){
  const r=rules.find(r=>r.id===id)!;r.categories.push('glass');
  r.exclude=[r.exclude,'olja|glass|granola|choklad|godis|brod|flingor'].filter(Boolean).join('|');
}
revise('pecan',{title:'^pecan|^pekannot',aliases:['pecans','pecan nuts','pecan halves']});
revise('coconut',{title:'^kokos riven|^riven kokos|^kokosflingor'});
revise('mustard',{title:'^senap$|^original senap|^senap original',ambiguous:true});
revise('cloves-dried',{title:'^nejlikor malen|^kryddnejlika.*malen'});
revise('vanilla-ice-cream',{basis:'l'});
for(const id of ['pepper-black','pepper-white','cinnamon','paprika','cayenne','cumin','nutmeg','ginger-dried',
  'cloves-dried','allspice','turmeric','coriander-dried','cardamom','chili-flakes','curry','oregano-dried','thyme-dried',
  'basil-dried','parsley-dried','rosemary-dried','sage-dried','tarragon-dried','dill-dried']){
  const r=rules.find(r=>r.id===id)!;
  r.exclude=[r.exclude,'granola|musli|grot|kaka|kex|brod|sas|sauce|soppa|mix|blend|godis|choklad'].filter(Boolean).join('|');
}
food('tomato-juice','tomato juice','^tomatjuice|^tomato juice','dryck','l');
food('plum-tomato','plum tomatoes|roma tomatoes','^plommontomat',produce);
food('white-chocolate-chips','white chocolate chips','^chokladknappar vit',shelf);
food('green-peppers','green peppers','paprika gron|gron paprika',produce);
food('broccoli-frozen','frozen broccoli|frozen broccoli florets','^broccoli buketter',frozen);
food('seasoning-salt','seasoning salt|seasoned salt','^aromat kryddsalt',shelf,'kg',{ambiguous:true});
food('tomato-stewed','stewed tomatoes','^hela tomater skalade|^tomater krossade',shelf,'kg',{ambiguous:true});
food('coconut-generic','coconut','^kokos riven',shelf,'kg',{ambiguous:true});
food('corn-generic','corn','^majs\\b',shelf,'kg',{ambiguous:true});
food('sweet-onion','sweet onion|sweet onions','^lok gul',produce,'kg',{ambiguous:true});
food('cornmeal-yellow','yellow cornmeal','^majsmjol',shelf);
food('plain-bread','bread|bread slices','^rostbrod|^formfranska','brod','kg',{ambiguous:true});
food('chili-sauce','chili sauce|sweet chili sauce','^sweet chili|^chilisauce|^chili sauce',shelf,'kg',{ambiguous:true});
food('vanilla-flavouring','vanilla essence|vanilla flavoring|vanilla flavouring','^vaniljarom',shelf,'l');
food('condensed-milk-unspecified','sweetened condensed milk|condensed milk','^kondenserad mjolk$',shelf,'kg',{ambiguous:true});
food('almond-slivers','slivered almonds|sliced almonds','^mandelspån|^mandelspan',shelf);
food('potato-fresh','fresh potatoes','^potatis',produce);
food('sunflower-oil-extra','safflower oil','safflorolja',shelf,'l');
revise('cinnamon',{title:'^kanel\\b'});
revise('cocoa',{title:'^kakao\\b',exclude:'dryck|blandning|kokos|granola|musli|grot|flingor|choklad'});
revise('ginger-dried',{exclude:'syltad|inlagd|dryck|marmelad|soppa|sas'});
revise('raisin',{title:'^russin\\b',exclude:'notter|musli|granola|grot|flingor|mix|choklad|dadlar'});
revise('sea-salt',{title:'^havssalt\\b|^flingsalt.*(?:naturell|jod)',exclude:'mineral|orter'});
revise('pineapple-canned',{ambiguous:true});
for(const id of ['chickpea','black-bean','kidney-bean','white-bean','pinto-bean'])revise(id,{ambiguous:true});
for(const id of ['dark-chocolate','milk-chocolate','white-chocolate'])revise(id,{exclude:'sas|sauce|flingor|granola|karamell|notter|kex|godis'});
// A keyword inside a cereal, sweet or prepared sauce is not the ingredient.
for(const r of rules)r.exclude=[r.exclude,'musli|granola|smoothie|knacke|proteinbar'].filter(Boolean).join('|');
for(const id of ['oregano-dried','thyme-dried','basil-dried','parsley-dried','rosemary-dried','sage-dried','tarragon-dried','dill-dried']){
  const r=rules.find(r=>r.id===id)!;r.title += '\\b';
}
revise('cranberry-dried',{title:'^tranbar torkade'});
revise('date',{title:'^(?:dates )?dadlar(?: torkade| eko|$)',exclude:'smak|choklad|lakrits|caramel|cola|musli|granola'});
revise('pistachio',{title:'^pistage(?:notter|not| )',exclude:'kram|glass|choklad|musli|granola|godis'});
revise('peanut',{exclude:'smor|salt|rosta|med skal|musli|granola|choklad'});
revise('blue-cheese',{exclude:'mjukost|smalt|sas'});
revise('bbq-sauce',{title:'^(?:bbq|barbecue|barbeque)',exclude:'korean|wok|marinad'});
revise('saffron',{title:'^saffran\\b',exclude:'ris|pasta|sas|soppa'});
revise('coffee-instant',{title:'^snabbkaffe',exclude:'cappuccino|latte|socker|choklad'});
revise('cloves-dried',{title:'^nejlikor mal(?:en|da)|^kryddnejlika.*mal'});
revise('cloves-whole',{title:'^nejlikor hela|^kryddnejlika.*hel'});
revise('apple-vinegar',{title:'^appelcider ?vinager'});
revise('creme-fraiche',{exclude:'latt|light|smak|tomat|chili|vitlok|saffran'});
revise('coconut-milk',{exclude:'latt|light|dryck|7%'});
revise('tortilla-corn',{exclude:'chip|wheat|vete',ambiguous:true});
revise('pumpkin',{exclude:'halloween',ambiguous:true});
revise('chicken-thigh',{ambiguous:true});
revise('chorizo',{exclude:'kyckling|kalkon|vego'});
revise('chicken-stock',{title:'^(?:kyckling ?buljong|honsbuljong|buljong kyckling)',ambiguous:true});
revise('vegetable-stock',{title:'^(?:gronsak.? ?buljong|buljong gronsak)',ambiguous:true});
revise('flour',{aliases:[...rules.find(r=>r.id==='flour')!.aliases,'unbleached all-purpose flour','unbleached all purpose flour']});
revise('chicken-breast',{aliases:[...rules.find(r=>r.id==='chicken-breast')!.aliases,'boneless skinless chicken breast halves']});
food('mint-extra','of fresh mint','^mynta',produce,'kg',{form:'fresh'});
food('catsup','catsup','^tomatketchup|^ketchup',shelf);
food('cranberry-frozen','frozen cranberries','^tranbar',frozen);
food('romano','romano cheese|pecorino romano cheese|pecorino romano','^pecorino romano',dairy);
food('liquid-smoke','liquid smoke','^liquid smoke',shelf,'l');
revise('hazelnut',{title:'^hasselnot(?:ter)?\\b',exclude:'kram|musli|granola|choklad|glass|godis'});
revise('peanut',{title:'^jordnot(?:ter)?\\b',exclude:'smor|salt|rosta|med skal|musli|granola|choklad'});
revise('pistachio',{title:'^pistage(?:notter|not)\\b',exclude:'marsipan|brod|kram|glass|choklad|musli|granola|godis'});
revise('walnut',{title:'^valnot(?:ter)?\\b'});
revise('shrimp',{ambiguous:true});
food('tomato-diced','canned diced tomatoes|diced tomatoes','^tomater tarnade|^tarnade tomater',shelf);
food('roquefort-specific','roquefort cheese','^roquefort',dairy);
food('lentil-brown','brown lentils','^bruna linser|^linser bruna',shelf,'kg',{ambiguous:true});
// Specific identities must not be shadowed by a generic rule with the same alias.
revise('tomato-canned',{aliases:['canned tomatoes','canned crushed tomatoes','crushed tomatoes']});
revise('blue-cheese',{aliases:['blue cheese']});
revise('lentil-green',{aliases:['lentils','green lentils']});
revise('almond',{aliases:['almonds','almond']});
revise('condensed-milk',{aliases:['sweetened condensed milk']});
revise('condensed-milk-unspecified',{aliases:['condensed milk']});
revise('cornmeal',{title:'^polenta',aliases:['cornmeal','corn meal']});
revise('cornmeal-yellow',{title:'^polenta'});
food('maize-flour','maize flour','^majsmjol',shelf);
// Verified cuts in the permitted-brand catalogue. Do not replace whole birds,
// unknown cuts, cooked meat or ground lamb with a different form/species.
revise('chicken-breast',{title:'^(?:kyckling ?(?:brost)?file|kycklingbrost file|brostfile kyckling)',
  aliases:[...rules.find(r=>r.id==='chicken-breast')!.aliases,'boneless chicken breast','skinless chicken breasts',
    'skinless chicken breast','skinless chicken breast halves','boneless skinless chicken breast half',
    'chicken breast fillets','chicken breast fillet']});
revise('chicken-thigh',{aliases:['chicken thighs','chicken thigh'],title:'kyckling ?lar',ambiguous:true});
food('chicken-thigh-fillet','boneless chicken thighs|boneless skinless chicken thighs|boneless skinless chicken thigh',
  '^kyckling ?larfile',meat+'|'+frozen,'kg',{exclude:'grill|tillagad|krydd|marinerad'});
food('chicken-drumstick','chicken drumsticks|chicken drumstick','^kycklingben',meat+'|'+frozen,'kg',{exclude:'grill|tillagad|krydd|marinerad'});
food('chicken-leg','chicken legs|chicken leg|chicken leg quarters|chicken leg quarter','^kyckling ?klubba',meat+'|'+frozen,'kg',{exclude:'grill|tillagad|krydd|marinerad'});
food('chicken-tenderloin','chicken tenderloins|chicken tenderloin','^kyckling ?innerfile',meat+'|'+frozen);
food('chicken-liver','chicken liver|chicken livers','^kycklinglever',meat+'|'+frozen);
food('chicken-gizzard','chicken gizzard|chicken gizzards','^kycklingmage',meat+'|'+frozen);
food('chicken-heart','chicken heart|chicken hearts','^kycklinghjarta',meat+'|'+frozen);
food('chicken-nuggets','chicken nuggets|frozen chicken nuggets','^kyckling nuggets',meat+'|'+frozen);
revise('chicken-wing',{aliases:['chicken wings','chicken wing']});
revise('beef-mince',{aliases:[...rules.find(r=>r.id==='beef-mince')!.aliases,'minced beef','hamburger meat']});
revise('beef-tenderloin',{aliases:[...rules.find(r=>r.id==='beef-tenderloin')!.aliases,'filet of beef','beef tenderloin steaks'],categories:[meat,frozen]});
food('lamb-shank','lamb shanks|lamb shank','^lammlagg',meat+'|'+frozen);
food('lamb-stew','lamb stew meat|lamb stewing meat','^lammgrytbitar',meat+'|'+frozen);
food('lamb-leg-bone','bone-in leg of lamb|leg of lamb with bone','^lammstek med ben',meat+'|'+frozen);
revise('chicken-bouillon-cube',{title:'^kyckling ?buljo(?:ng|n).*tarning',basis:'piece'});
export const FOOD_RULES: readonly FoodRule[] = rules;
